name: Release starchitect provider

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required for creating releases
    
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build binary for ${{ matrix.goos }}_${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          BINARY_NAME=terraform-provider-starchitect
          
          # Build the binary
          go build -o ${BINARY_NAME} .
          
          # Create zip file with OS and architecture in name
          zip terraform-provider-starchitect_${{ matrix.goos }}_${{ matrix.goarch }}.zip ${BINARY_NAME}

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: terraform-provider-starchitect_*_*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
